// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/Contact.tsx";
import * as $1 from "./routes/Experience.tsx";
import * as $2 from "./routes/Projects.tsx";
import * as $3 from "./routes/_app.tsx";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/About.tsx";
import * as $$1 from "./islands/Banner.tsx";

const manifest = {
  routes: {
    "./routes/Contact.tsx": $0,
    "./routes/Experience.tsx": $1,
    "./routes/Projects.tsx": $2,
    "./routes/_app.tsx": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/About.tsx": $$0,
    "./islands/Banner.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
