// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/Blogs.tsx";
import * as $1 from "./routes/Resume.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/About.tsx";
import * as $$1 from "./islands/Banner.tsx";
import * as $$2 from "./islands/Contact.tsx";
import * as $$3 from "./islands/Experience.tsx";
import * as $$4 from "./islands/Header.tsx";
import * as $$5 from "./islands/MobileHeader.tsx";
import * as $$6 from "./islands/Projects.tsx";
import * as $$7 from "./islands/Skills.tsx";
import * as $$8 from "./islands/Testimonials.tsx";

const manifest = {
  routes: {
    "./routes/Blogs.tsx": $0,
    "./routes/Resume.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/About.tsx": $$0,
    "./islands/Banner.tsx": $$1,
    "./islands/Contact.tsx": $$2,
    "./islands/Experience.tsx": $$3,
    "./islands/Header.tsx": $$4,
    "./islands/MobileHeader.tsx": $$5,
    "./islands/Projects.tsx": $$6,
    "./islands/Skills.tsx": $$7,
    "./islands/Testimonials.tsx": $$8,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
